apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: peoject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: docker6767/image
        ports:
        - containerPort: 80
