apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dev2
  labels:
    app: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: dilip1690/project-image
        ports:
        - containerPort: 80
